# Default values for Grafana OnCall

# i.e. example.com
base_url: ildari.me

image:
  # TODO: use our public repo
  repository: registry.digitalocean.com/ildar-testing/hobby-oncall-2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# TODO: remove this after we use public image
imagePullSecrets:
  - name: "registry-ildar-testing"

engine:
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

celery:
  replicaCount: 1
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

env: []

service:
  enabled: false
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
#  className: ""
#  annotations: {}
##     kubernetes.io/ingress.class: nginx
##     kubernetes.io/tls-acme: "true"
#  hosts: []
##    - host: oncall.example.com
##      paths:
##        - path: /
##          pathType: ImplementationSpecific
#  tls:  # []
##    - secretName: oncall-example-com-tls
##      hosts:
##        - oncall.example.com

nginx-ingress:
  enabled: true

cert-manager:
  enabled: true
  installCRDs: true
  webhook:
    timeoutSeconds: 30
    # cert-manager tries to use the already used port, changing to another one
    # https://github.com/cert-manager/cert-manager/issues/3237
    # https://cert-manager.io/docs/installation/compatibility/#gke-autopilot
    securePort: 10261
  podDnsPolicy: None
  podDnsConfig:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1

# Additional services configuration
# We recommend using external services to reduce the overhead of managing statefule services
mariadb:
  enabled: true
  auth:
    database: oncall

externalMysql:
  host:
  port:
  db_name:
  user:
  password:

rabbitmq:
  enabled: true

externalRabbitmq:
  host:
  port:
  user:
  password:

redis:
  enabled: true

external_redis:
  host:
  password:

grafana:
  enabled: true
  grafana.ini:
    server:
      domain: example.com
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  persistence:
    enabled: true
  plugins:
    - grafana-oncall-app

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


ildar:
  enabled: true